version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=password
    volumes: 
      - db:/var/lib/mysql
    networks:
      - inception

  wordpress:
    depends_on: 
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  webserver:
    depends_on:
      - wordpress
    image: nginx
    build:
      context: ./requirements/nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - inception

volumes:
  db:
    driver: local
    driver_opts:
      device: /home/mnikolov/data/database
      type: volume
      o: bind
  wordpress:
    driver: local
    driver_opts:
      device: /home/mnikolov/data/wordpress
      type: volume
      o: bind

networks:
  inception:
    driver: bridge